[project]
name = "chronos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "python-dotenv>=1.1.0",
    "python-telegram-bot[job-queue]>=22.1",
    "pytz>=2025.2",
    "sqlalchemy>=2.0.0",
    "pillow>=10.0.0",
]

[project.scripts]
chronos = "chronos.main:main"
