name: Deploy to Production Server

on:
  push:
    branches:
      - prod  # Trigger this workflow on pushes to the 'prod' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server via TailScale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Deploy
        run: |
          ssh lyla.shrimp-fujita.ts.net
          bash bash /home/vaibhav/my-debauch-devotion/deploy.sh
