name: Deploy to Production Server

on:
  push:
    branches:
      - prod  # Trigger this workflow on pushes to the 'prod' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server via TailScale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Configure SSH known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - name: Run Deployment Script
        run: |
          ssh deploy@${{ secrets.REMOTE_HOST }} 'bash /home/vaibhav/my-debauch-devotion/deploy.sh'
